### ISSUE TITLE
huggingface.co/spaces/mimbres/YourMT3    has runtime error

### ISSUE THREAD

**Issue by ganxiaozhe23** [mimbres/YourMT3#4]
runtime error
Exit code: 1. Reason: Traceback (most recent call last):
  File "/home/user/app/app.py", line 13, in <module>
    from model_helper import *
  File "/home/user/app/model_helper.py", line 20, in <module>
    from model.ymt3 import YourMT3
  File "/home/user/app/amt/src/model/ymt3.py", line 21, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'
Container logs:

===== Application Startup at 2024-08-09 17:54:37 =====

Traceback (most recent call last):
  File "/home/user/app/app.py", line 13, in <module>
    from model_helper import *
  File "/home/user/app/model_helper.py", line 20, in <module>
    from model.ymt3 import YourMT3
  File "/home/user/app/amt/src/model/ymt3.py", line 21, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'
Traceback (most recent call last):
  File "/home/user/app/app.py", line 13, in <module>
    from model_helper import *
  File "/home/user/app/model_helper.py", line 20, in <module>
    from model.ymt3 import YourMT3
  File "/home/user/app/amt/src/model/ymt3.py", line 21, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'

**Comment by Youho99** [comment]
+1

**Comment by Youho99** [comment]
CPU version space is available i see : 

https://huggingface.co/spaces/mimbres/YourMT3-cpu

**Comment by mimbres** [comment]
@Youho99 Thanks for reporting the issue. Actually, two issues started happening from Friday. 
1. In the latest version of `wandb`, errors keep occurring when wandb is disabled. 
2. Huggingface IP was blocked on YouTube.

I've fixed the first issue, but `youtube download` may still not work. For testing on YouTube, use Google Colab. I originally used `pytube` and then switched to `yt-dlp`, but the issue with the IP being blocked doesn’t seem easy to resolve.
